---
title: "task_response_analysis"
output: html_document
---

```{r libraries, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(fig.align="center") 
library(rstanarm)
library(tidyverse)
library(tidybayes)
library(modelr) 
library(ggplot2)
library(magrittr)  
library(emmeans)
library(bayesplot)
library(brms)
library(gganimate)

theme_set(theme_light())

```

# num_of_interacted_variable_set_split.csv, num_interacted_variable_set
# num_of_interacted_visual_design_split.csv, num_interacted_visual_design
# num_of_exposed_visual_design_split.csv, num_exposed_visual_design
# num_of_exposed_variable_set_split.csv, num_exposed_variable_set

```{r}
model1 <- analysis("num_of_interacted_variable_set_split.csv", "num_interacted_variable_set", 35.24, 25.33)
model2 <- analysis("num_of_interacted_visual_design_split.csv", "num_interacted_visual_design", 35.90, 25.25)
model3 <- analysis("num_of_exposed_visual_design_split.csv", "num_exposed_visual_design", 121.58, 89.78)
model4 <-analysis("num_of_exposed_variable_set_split.csv", "num_exposed_variable_set", 138.94, 120.45)
```

```{r interaction_analysis}
analysis = function(filename, col, prior_mean, prior_sd) {
  data <- read.csv(filename)
  task_list <- c("3. Prediction", "4. Exploration")
  seed = 12
  
  
  data <- data %>%
    mutate(
      dataset = as.factor(dataset),
      oracle = as.factor(oracle),
      search = as.factor(search),
      task = as.factor(task)
    )
stanvars <- stanvar(prior_mean, name='prior_mean') + stanvar(prior_sd, name='prior_sd')
  model <- brm(
    formula = as.formula(paste(col, "~ oracle * search + dataset + task + (1 | participant_id)")),
    prior = prior(normal(prior_mean, prior_sd), class = Intercept),
    chains = 2,
    cores = 2,
    iter = 2500,
    warmup = 1000,
    data = data,
    stanvars=stanvars
  )
  
  summary(model)
  
  pairs(
    model,
    pars = c(
      "b_Intercept",
      "b_datasetmovies",
      "b_oracledziban",
      "b_searchdfs",
      "b_task4.Exploration"
    ),
    fixed = TRUE
  )
  
  draw_data <- data %>%
    add_fitted_draws(model, seed = seed, re_formula = NA)
  draw_data$condition <- paste(draw_data$oracle, draw_data$search)
  
   plot <- draw_data %>% ggplot(aes(x = oracle, y = .value)) +
      stat_eye(.width = c(.95, .5)) +
      theme_minimal() +
      facet_grid(task ~ search)
    
    plot
    
    filename = gsub(" ", "", filename)
    
     ggsave(
      file = paste(filename, ".png", sep = ""),
      plot = plot,
      path = paste0("../plots/posterior_draws/",col)
    )
     
     fit_info <-
      draw_data %>% group_by(search, oracle, task) %>% mean_qi(.value, .width = c(.95, .5))
    fit_info
    
    write.csv(
      fit_info,
      paste(
        "../plot_data/posterior_draws/",col,"/",
        filename,
        ".csv",
        sep = ""
      ),
      row.names = FALSE
    )
    
    plot_dataset <- plot + aes(fill = dataset, alpha = 0.5)
    
    ggsave(
      file = paste(filename, "_split_by_dataset.png", sep = ""),
      plot = plot_dataset,
      path = paste0("../plots/posterior_draws/",col)
    )
    fit_info_dataset <-
      draw_data %>% group_by(search, oracle, dataset) %>% mean_qi(.value, .width = c(.95, .5))
    fit_info_dataset
    write.csv(
      fit_info_dataset,
      paste(
        "../plot_data/posterior_draws/",col,"/",
        filename,
        "_split_by_dataset.csv",
        sep = ""
      ),
      row.names = FALSE
    )
  
  ############################################################################
  predictive_data <- data %>%
    add_predicted_draws(model, seed = seed, re_formula = NA)
  
  diff_in_search_prediction <- predictive_data %>%
    group_by(search, task, dataset, .draw) %>%
    summarize(value = weighted.mean(.prediction)) %>%
    compare_levels(value, by = search) %>%
    rename(diff = value)
  
  diff_in_search_prediction_plot <- diff_in_search_prediction %>%
    ggplot(aes(x = diff, y = task)) +
    xlab(
      paste0(
        "Difference in ",col,"(",
        diff_in_search_prediction[1, 'search'],
        ")"
      )
    ) +
    ylab("Task") +
    stat_halfeye(.width = c(.95, .5)) +
    geom_vline(xintercept = 0, linetype = "longdash") +
    theme_minimal() + scale_y_discrete(limits = rev(levels(diff_in_search_prediction$task)))
  
  ggsave(
    file = "search_differences.png",
    plot = diff_in_search_prediction_plot,
    path = paste0("../plots/comparisons/",col),
    width = 7,
    height = 7
  )
  
  diff_in_search_prediction_intervals <-
    diff_in_search_prediction %>% group_by(search, task) %>% mean_qi(diff, .width = c(.95, .5))
  
  write.csv(
    diff_in_search_prediction_intervals,
    paste0("../plot_data/comparisons/",col,"/search_differences.csv"),
    sep = "",
    row.names = FALSE
  )
  
  diff_in_search_prediction_plot_split_by_dataset <-
    diff_in_search_prediction_plot + facet_grid(. ~ dataset) + aes(fill = dataset)
  
  ggsave(
    file = "split_by_dataset_search_differences.png",
    plot = diff_in_search_prediction_plot_split_by_dataset,
    path = paste0("../plots/comparisons/",col),
    width = 7,
    height = 7
  )
  
  diff_in_search_prediction_intervals_split_by_dataset <-
    diff_in_search_prediction %>% group_by(search, dataset, task) %>% mean_qi(diff, .width = c(.95, .5))
  
  write.csv(
    diff_in_search_prediction_intervals_split_by_dataset,
    paste0("../plot_data/comparisons/",col,"/search_differences_split_by_dataset.csv"),
    row.names = FALSE
  )
  
  ############
 predictive_data <- data %>%
    add_predicted_draws(model, seed = seed, re_formula = NA)
  
  diff_in_oracle_prediction <- predictive_data %>%
    group_by(oracle, task, dataset, .draw) %>%
    summarize(value = weighted.mean(.prediction)) %>%
    compare_levels(value, by = oracle) %>%
    rename(diff = value)
  
  diff_in_oracle_prediction_plot <- diff_in_oracle_prediction %>%
    ggplot(aes(x = diff, y = task)) +
    xlab(
      paste0(
        "Difference in ",col,"(",
        diff_in_oracle_prediction[1, 'oracle'],
        ")"
      )
    ) +
    ylab("Task") +
    stat_halfeye(.width = c(.95, .5)) +
    geom_vline(xintercept = 0, linetype = "longdash") +
    theme_minimal() + scale_y_discrete(limits = rev(levels(diff_in_oracle_prediction$task)))
  
  ggsave(
    file = "oracle_differences.png",
    plot = diff_in_oracle_prediction_plot,
    path = paste0("../plots/comparisons/",col),
    width = 7,
    height = 7
  )
  
  diff_in_oracle_prediction_intervals <-
    diff_in_oracle_prediction %>% group_by(oracle, task) %>% mean_qi(diff, .width = c(.95, .5))
  
  write.csv(
    diff_in_oracle_prediction_intervals,
    paste0("../plot_data/comparisons/",col,"/oracle_differences.csv"),
    sep = "",
    row.names = FALSE
  )
  
  diff_in_oracle_prediction_plot_split_by_dataset <-
    diff_in_oracle_prediction_plot + facet_grid(. ~ dataset) + aes(fill = dataset)
  
  ggsave(
    file = "split_by_dataset_oracle_differences.png",
    plot = diff_in_oracle_prediction_plot_split_by_dataset,
    path = paste0("../plots/comparisons/",col),
    width = 7,
    height = 7
  )
  
  diff_in_oracle_prediction_intervals_split_by_dataset <-
    diff_in_oracle_prediction %>% group_by(oracle, dataset, task) %>% mean_qi(diff, .width = c(.95, .5))
  
  write.csv(
    diff_in_oracle_prediction_intervals_split_by_dataset,
    paste0("../plot_data/comparisons/",col,"/oracle_differences_split_by_dataset.csv"),
    row.names = FALSE
  )
  return(model)
}
```

```{r num_interacted_variable_set}
data <- read.csv('num_of_interacted_variable_set_split.csv')
task_list <- c("3. Prediction", "4. Exploration")
seed = 12

data <- data %>%
  mutate(
    dataset = as.factor(dataset),
    oracle = as.factor(oracle),
    search = as.factor(search),
    task = as.factor(task)
  )
model <- brm(
    formula = bf(num_interacted_variable_set ~ dataset * oracle * search * task),
    chains = 2,
    cores = 2,
    iter = 2500,
    warmup = 1000,
    data = data,
  )

summary(model)

pairs(
  model,
  pars = c("b_Intercept",
          "b_datasetmovies",
           "b_oracledziban",
           "b_searchdfs",
            "b_task4.Exploration"),
  fixed = TRUE
)

draw_data <- data %>%
  add_fitted_draws(model, seed = seed, re_formula = NA)
draw_data$condition <- paste(draw_data$oracle, draw_data$search)

for (task_name in task_list) {
  draw_data_sub <- subset(draw_data, task == task_name)
  
  plot <- draw_data_sub %>% ggplot(aes(x = oracle, y = .value)) +
  stat_eye(.width = c(.95, .5)) +
  theme_minimal() +
  facet_grid(. ~ search)
  
  plot
  
  filename = gsub("^.*\\.","", task_name )
  filename = gsub(" ", "", filename)

  ggsave(
    file = paste(filename, ".png", sep = ""),
    plot = plot,
    path = "../plots/posterior_draws/num_interacted_variable_set"
  )
  
  fit_info <- draw_data_sub %>% group_by(search, oracle, dataset) %>% mean_qi(.value, .width = c(.95, .5))
  fit_info
  write.csv(fit_info,
            paste("../plot_data/posterior_draws/num_interacted_variable_set/", filename, ".csv", sep = ""),
            row.names = FALSE)
}

############################################################################
predictive_data <- data %>%
  add_predicted_draws(model, seed = seed, re_formula = NA)

diff_in_search_prediction <- predictive_data %>% 
  group_by(search, task, dataset, .draw) %>%
   summarize(num_interacted_variable_set = weighted.mean(.prediction)) %>%
   compare_levels(num_interacted_variable_set, by = search) %>%
   rename(diff_in_num_interacted_variable_set = num_interacted_variable_set) 

diff_in_search_prediction_plot <- diff_in_search_prediction %>%
      ggplot(aes(x = diff_in_num_interacted_variable_set, y = task)) +
      xlab(paste0("Difference in Number Interacted Variable Set (",diff_in_search_prediction[1,'search'],")")) +
      ylab("Task")+
      stat_halfeye(.width = c(.95, .5)) +
      geom_vline(xintercept = 0, linetype = "longdash") +
      theme_minimal() + scale_y_discrete(limits = rev(levels(diff_in_search_prediction$task)))

ggsave(file="search_differences.png", plot=diff_in_search_prediction_plot, path = "../plots/comparisons/num_interacted_variable_set", width = 7, height = 7)

diff_in_search_prediction_intervals <- diff_in_search_prediction %>% group_by(search, task) %>% mean_qi(diff_in_num_interacted_variable_set, .width = c(.95, .5))

write.csv(diff_in_search_prediction_intervals, "../plot_data/comparisons/num_interacted_variable_set/search_differences.csv", sep="", row.names = FALSE)

diff_in_search_prediction_plot_split_by_dataset <- diff_in_search_prediction_plot+facet_grid(. ~ dataset) + aes(fill= dataset)

ggsave(file="split_by_dataset_search_differences.png", plot=diff_in_search_prediction_plot_split_by_dataset, path = "../plots/comparisons/num_interacted_variable_set", width = 7, height = 7)

diff_in_search_prediction_intervals_split_by_dataset <- diff_in_search_prediction %>% group_by(search, dataset, task) %>% mean_qi(diff_in_num_interacted_variable_set, .width = c(.95, .5))

write.csv(diff_in_search_prediction_intervals_split_by_dataset, "../plot_data/comparisons/num_interacted_variable_set/search_differences_split_by_dataset.csv", row.names = FALSE)

############
diff_in_oracle_prediction <- predictive_data %>% 
  group_by(oracle, task, dataset, .draw) %>%
   summarize(num_interacted_variable_set = weighted.mean(.prediction)) %>%
   compare_levels(num_interacted_variable_set, by = oracle) %>%
   rename(diff_in_num_interacted_variable_set = num_interacted_variable_set) 

diff_in_oracle_prediction_plot <- diff_in_oracle_prediction %>%
      ggplot(aes(x = diff_in_num_interacted_variable_set, y = task)) +
      xlab(paste0("Difference in Number Interacted Variable Set (",diff_in_oracle_prediction[1,'oracle'],")")) +
      ylab("Task")+
      stat_halfeye(.width = c(.95, .5)) +
      geom_vline(xintercept = 0, linetype = "longdash") +
      theme_minimal() + scale_y_discrete(limits = rev(levels(diff_in_oracle_prediction$task)))

ggsave(file="oracle_differences.png", plot=diff_in_oracle_prediction_plot, path = "../plots/comparisons/num_interacted_variable_set", width = 7, height = 7)

diff_in_oracle_prediction_intervals <- diff_in_oracle_prediction %>% group_by(oracle, task) %>% mean_qi(diff_in_num_interacted_variable_set, .width = c(.95, .5))

write.csv(diff_in_oracle_prediction_intervals, "../plot_data/comparisons/num_interacted_variable_set/oracle_differences.csv", sep="", row.names = FALSE)

diff_in_oracle_prediction_plot_split_by_dataset <- diff_in_oracle_prediction_plot+facet_grid(. ~ dataset) + aes(fill= dataset)

ggsave(file="split_by_dataset_oracle_differences.png", plot=diff_in_oracle_prediction_plot_split_by_dataset, path = "../plots/comparisons/num_interacted_variable_set", width = 7, height = 7)

diff_in_oracle_prediction_intervals_split_by_dataset <- diff_in_oracle_prediction %>% group_by(oracle, dataset, task) %>% mean_qi(diff_in_num_interacted_variable_set, .width = c(.95, .5))

write.csv(diff_in_oracle_prediction_intervals_split_by_dataset, "../plot_data/comparisons/num_interacted_variable_set/oracle_differences_split_by_dataset.csv", row.names = FALSE)
```



<!-- ```{r task_response_ordinal} -->
<!-- analyses = c("confidence.udata", "confidence.ans", "efficiency", "ease.of.use", "utility", "overall") -->
<!-- confidence_metrics = c("confidence.udata", "confidence.ans") -->
<!-- preference_metrics = c("efficiency", "ease.of.use", "utility", "overall") -->

<!-- differences = c("search", "oracle", "alg") -->
<!-- seed = 12 -->

<!-- data <- read.csv('processed_ptask_responses.csv') -->
<!-- data[,analyses] <- lapply(data[,analyses],ordered) -->
<!-- data <- data %>% -->
<!--   mutate( -->
<!--     dataset = as.factor(dataset), -->
<!--     oracle = as.factor(oracle), -->
<!--     search = as.factor(search), -->
<!--     task = as.factor(task) -->
<!--   ) -->

<!-- generate_model_and_draws = function(data, attr, generate_eval_plots = FALSE) { -->
<!--   filename = gsub("\\.", "_", attr) -->
<!--   data$y = data[,attr] -->
<!--   model <- brm( -->
<!--     formula = bf(y ~ dataset * oracle * search * task), -->
<!--     family = cumulative("probit"), -->
<!--     prior = prior(normal(.26, 1.26), class = Intercept), -->
<!--     chains = 2, -->
<!--     cores = 2, -->
<!--     iter = 2500, -->
<!--     warmup = 1000, -->
<!--     data = data, -->
<!--     control = list(adapt_delta = 0.99), -->
<!--     file = filename, -->
<!--     seed = seed -->
<!--   ) -->
<!--   if(generate_eval_plots){ -->
<!--     # check that Rhat is close to 1, Bult_ESS is in the thousands -->
<!--     summary(model) -->
<!--     plot(model) -->

<!--   pairs( -->
<!--     model, -->
<!--     pars = c( -->
<!--       "b_Intercept[1]", -->
<!--       "b_Intercept[2]", -->
<!--       "b_Intercept[3]" -->
<!--     ), -->
<!--     fixed = TRUE -->
<!--   ) -->

<!--   pairs( -->
<!--     model, -->
<!--     pars = c( -->
<!--       "b_datasetmovies", -->
<!--       "b_oracledziban", -->
<!--       "b_searchdfs" -->
<!--     ), -->
<!--     fixed = TRUE -->
<!--   ) -->

<!--   data %>% -->
<!--     mutate(rating = y) %>% -->
<!--     ggplot(aes(x = oracle, fill = rating)) + -->
<!--     geom_bar() + -->
<!--     theme_minimal() + -->
<!--     facet_grid(. ~ search) -->

<!--   data %>% -->
<!--     add_predicted_draws(model, seed = seed) %>% -->
<!--     group_by(search, oracle, dataset) %>% -->
<!--     summarize(rating = .prediction) %>% -->
<!--     ggplot(aes(x = oracle, fill = rating)) + -->
<!--     geom_bar() + -->
<!--     theme_minimal() + -->
<!--     facet_grid(. ~ search) -->

<!--   spec <- data %>% -->
<!--     add_predicted_draws(model, seed = seed, n = 50) %>% -->
<!--     mutate(rating = .prediction) %>% -->
<!--     ggplot(aes(x = oracle, fill = rating)) + -->
<!--     geom_bar() + -->
<!--     theme_minimal() + -->
<!--     facet_grid(. ~ search) + -->
<!--     transition_manual(.draw) -->

<!--     animate(spec, fps = 2.5) -->

<!--     spec2 <- data %>% -->
<!--   add_predicted_draws(model, seed = 14, n = 50) %>% -->
<!--     mutate( -->
<!--       observed = ordered(y, levels=c("-2","-1", "0", "1", "2")), -->
<!--       predicted = ordered(.prediction, levels=c("-2",-"1", "0", "1", "2"))) %>% -->
<!--     pivot_longer(cols = c("observed", "predicted"), names_to = "source", values_to = "rating") %>% -->
<!--     ggplot(aes(x = rating, fill = source)) + -->
<!--       geom_bar(position = position_dodge()) + -->
<!--       theme_minimal() + -->
<!--       facet_wrap(. ~ participant_id) + -->
<!--       transition_manual(.draw) -->

<!--   animate(spec2, fps = 2.5) -->
<!--   } -->

<!--   predictive_plot_data <- data %>% -->
<!--     add_predicted_draws(model, seed = seed, re_formula = NA) %>% -->
<!--     group_by(search, oracle, .draw) %>% -->
<!--     mutate(rating = weighted.mean(as.numeric(as.character(.prediction)))) -->

<!--   predictive_plot <- predictive_plot_data %>% -->
<!--     ggplot(aes(x = oracle, y = rating)) + -->
<!--     stat_eye(.width = c(.95, .5)) + -->
<!--     theme_minimal() + -->
<!--     coord_cartesian(ylim = c(-2, 2)) + -->
<!--     facet_grid(. ~ search) -->

<!--   ggsave(file=paste(filename, ".png", sep=""), plot=predictive_plot, path = "../plots/posterior_draws/user_response", width = 7, height = 7) -->
<!--   credible_intervals <- predictive_plot_data %>% group_by(search, oracle) %>% mean_qi(rating, .width = c(.95, .5)) -->
<!--   write.csv(credible_intervals, paste("../plot_data/posterior_draws/user_response/",filename,".csv", sep=""), row.names = FALSE, append=FALSE) -->

<!--   predictive_plot_focused_open_split <- predictive_plot_data %>% -->
<!--     ggplot(aes(x = oracle, y = rating, fill=search, alpha = 0.5)) + -->
<!--     stat_eye(.width = c(.95, .5)) + -->
<!--     theme_minimal() + -->
<!--     coord_cartesian(ylim = c(-2, 2)) + -->
<!--     facet_grid(. ~ task_type) -->

<!--   ggsave(file=paste(filename, "_focused_open_split.png", sep=""), plot=predictive_plot_focused_open_split, path = "../plots/posterior_draws/user_response", width = 7, height = 7) -->
<!--   credible_intervals <- predictive_plot_data %>% group_by(search, oracle, task_type) %>% mean_qi(rating, .width = c(.95, .5)) -->
<!--   write.csv(credible_intervals, paste("../plot_data/posterior_draws/user_response/",filename,"_focused_open_split.csv", sep=""), row.names = FALSE, append=FALSE) -->

<!--   return(model) -->
<!-- } -->
<!-- draw_data_combined <- list() -->
<!-- differences_intervals <- list() -->

<!-- for (diff in differences){ -->
<!--   draw_data_combined[[diff]] <- data.frame() -->
<!--   differences_intervals[[diff]] <- data.frame() -->
<!-- } -->

<!-- get_differences_and_intervals = function(draws, variable_to_compare, metric){ -->
<!--   difference_data <- draw_data %>% -->
<!--     group_by(!!sym(variable_to_compare), .draw) %>% -->
<!--     summarize(rating = weighted.mean(as.numeric(.prediction))) %>% -->
<!--     compare_levels(rating, by = !!sym(variable_to_compare)) %>% -->
<!--     rename(diff_in_rating = rating)  -->

<!--   difference_data['metric'] = metric -->
<!--   difference_credible_intervals <- difference_data %>% mean_qi(diff_in_rating, .width = c(.95, .5)) -->
<!--   difference_credible_intervals['metric'] = metric -->

<!--   return(list("differences" = difference_data, "intervals" = difference_credible_intervals)) -->
<!-- } -->

<!-- for (attr in analyses) { -->
<!--   model = generate_model_and_draws(data, attr) -->
<!--   draw_data <- data %>% -->
<!--   add_predicted_draws(model, seed = seed, re_formula = NA)  -->

<!--   draw_data$alg <- paste(draw_data$search, draw_data$oracle) -->

<!--   for (diff in differences){ -->
<!--     vals <- get_differences_and_intervals(draw_data, diff, attr) -->
<!--     draw_data_combined[[diff]] <- rbind(draw_data_combined[[diff]], vals$differences) -->
<!--     differences_intervals[[diff]] <- rbind(differences_intervals[[diff]], vals$intervals) -->
<!--   } -->
<!-- } -->

<!-- # flip order so that we get bfs - dfs -->
<!-- if(draw_data_combined$search[1,'search']=="dfs - bfs"){ -->
<!--   draw_data_combined$search$search = 'bfs - dfs' -->
<!--   draw_data_combined$search$diff_in_rating = -1 * draw_data_combined$search$diff_in_rating -->
<!-- } -->

<!-- if(differences_intervals$search[1,'search']=="dfs - bfs"){ -->
<!--   differences_intervals$search$search = 'bfs - dfs' -->
<!--   differences_intervals$search$temp = -1 * differences_intervals$search$.lower -->
<!--   differences_intervals$search$diff_in_rating = -1 * differences_intervals$search$diff_in_rating -->
<!--   differences_intervals$search$lower = -1 * differences_intervals$search$.upper -->
<!--   differences_intervals$search$.upper = differences_intervals$search$temp  -->
<!-- } -->

<!-- generate_difference_plot = function(data, xLab, yLab, filename){ -->
<!--    difference_plot <- data %>% -->
<!--       ggplot(aes(x = diff_in_rating, y = metric)) + -->
<!--       ylab(yLab) + -->
<!--       xlab(xLab) + -->
<!--       stat_halfeye(.width = c(.95, .5)) + -->
<!--       geom_vline(xintercept = 0, linetype = "longdash") + -->
<!--       theme_minimal() -->
<!--     ggsave(file=filename, plot=difference_plot, path = "../plots/comparisons/user_response", width = 7, height = 7) -->
<!-- } -->

<!-- generate_confidence_and_preference_plots = function(data, variable_to_compare){ -->
<!--   data$metric <- factor(data$metric, levels=rev(analyses)) -->

<!--   generate_difference_plot(subset(data, metric %in% confidence_metrics), -->
<!--                             paste0("Expected Difference in Rating (",data[1,variable_to_compare],")"), -->
<!--                             "Confidence", -->
<!--                            paste0(variable_to_compare, "_rating_differences_confidence.png") -->
<!--                             ) -->

<!--   generate_difference_plot(subset(data, metric %in% preference_metrics), -->
<!--                             paste0("Expected Difference in Rating (",data[1,variable_to_compare],")"), -->
<!--                             "Preference", -->
<!--                            paste0(variable_to_compare, "_rating_differences_preference.png") -->
<!--                             ) -->
<!-- } -->

<!-- for (diff in differences){ -->
<!--   subsetted_draw_data <- data.frame() -->
<!--   if(diff=="alg"){ -->
<!--     subsetted_draw_data <- subset(draw_data_combined[[diff]], alg == "dfs compassql - bfs dziban") -->
<!--     } -->
<!--   else { -->
<!--     subsetted_draw_data <- draw_data_combined[[diff]] -->
<!--   } -->

<!--   generate_confidence_and_preference_plots(subsetted_draw_data, diff) -->
<!--   write.csv(differences_intervals[[diff]], paste0("../plot_data/comparisons/user_response/",diff, "_rating_differences.csv"), row.names = FALSE) -->
<!-- } -->

<!-- ``` -->


<!-- # ```{r time_analysis_focused_or_open}   -->
<!-- # # The different tasks can be decribed as "focused" or "open-ended", so let's run analyses where we split on that attribute -->
<!-- # run_model_time(subset(time_data, task_type == "Focused"), "Focused", prior_mean, prior_sd) -->
<!-- # run_model_time(subset(time_data, task_type == "Open-Ended"), "Open-Ended", prior_mean, prior_sd) -->
<!-- # ``` -->


<!-- ```{r accuracy_analysis} -->

<!-- accuracy_data = read.csv('processed_accuracy_split.csv') -->
<!-- differences = c("search", "oracle") -->
<!-- analyses = c("confidence.udata", "confidence.ans", "efficiency", "ease.of.use", "utility", "overall") -->
<!-- confidence_metrics = c("confidence.udata", "confidence.ans") -->
<!-- preference_metrics = c("efficiency", "ease.of.use", "utility", "overall") -->
<!-- seed = 12 -->

<!-- accuracy_data = read.csv('processed_accuracy_split.csv') -->
<!-- accuracy_tasks = c("1. Find Extremum", "2. Retrieve Value") -->
<!-- accuracy_data$oracle = as.factor(accuracy_data$oracle) -->
<!-- accuracy_data$search = as.factor(accuracy_data$search) -->
<!-- accuracy_data$dataset = as.factor(accuracy_data$dataset) -->


<!-- generate_accuracy_model_and_draws = function(data){ -->
<!--   model_binary <- brm(accuracy ~ oracle*search+dataset,  -->
<!--                     data = data, -->
<!--                     prior = c(prior(normal(1, .05), class = Intercept)), -->
<!--                     family = bernoulli(link = "logit"), -->
<!--                     warmup = 500,  -->
<!--                     iter = 3000,  -->
<!--                     chains = 2,  -->
<!--                     cores=2, -->
<!--                     seed=seed -->
<!--                     ) -->

<!--   # START evaluation -->
<!--   if (FALSE){ -->

<!--   data %>% -->
<!--     select(-accuracy) %>% -->
<!--     add_predicted_draws(model_binary, prediction = "accuracy", seed = seed) %>% -->
<!--     ggplot(aes(x = accuracy)) + -->
<!--     geom_density(fill = "black", size = 0) + -->
<!--     scale_y_continuous(NULL, breaks = NULL) + -->
<!--     labs(subtitle = "Prior predictive distribution for correctness") + -->
<!--     theme(panel.grid = element_blank()) -->

<!--   stanplot(model_binary, type="trace") -->
<!--   stanplot(model_binary, type="acf_bar") -->
<!--   summary(model_binary) -->
<!--   stanplot(model_binary, type="areas", prob=0.95) -->
<!--   exp(fixef(model_binary)[,-2]) -->

<!--   plot(model_binary) -->
<!--   pairs(model_binary) -->

<!--   pred <- predict(model_binary, type = "response") -->
<!--   pred <- if_else(pred[,1] > 0.5, 1, 0) -->
<!--   confusion_matrix <- table(pred, pull(data, accuracy))  -->
<!--   } -->
<!--   # END evalutation -->
<!--   #  -->
<!--   # posterior_draws <- data %>% -->
<!--   #     add_fitted_draws(model_binary, seed = seed, re_formula = NA) %>% -->
<!--   #     group_by(search, oracle, dataset, .draw) -->
<!--   # posterior_plot <- posterior_draws %>% -->
<!--   #     ggplot(aes(x = oracle, y = .value)) + -->
<!--   #     stat_eye(.width = c(.95, .5)) + -->
<!--   #     theme_minimal() + -->
<!--   #     coord_cartesian(ylim = c(0, 1)) + -->
<!--   #     facet_grid(. ~ search) -->

<!--   return(model_binary) -->
<!-- } -->
<!-- draw_data_combined <- list() -->
<!-- differences_intervals <- list() -->

<!-- for (diff in differences){ -->
<!--   draw_data_combined[[diff]] <- data.frame() -->
<!--   differences_intervals[[diff]] <- data.frame() -->
<!-- } -->

<!-- all_draws <- data.frame() -->

<!-- get_differences_and_intervals = function(predictive_data, variable_to_compare, metric){ -->
<!--   difference_data <- predictive_data %>% -->
<!--     group_by(!!sym(variable_to_compare), dataset, .draw) %>% -->
<!--     summarize(accuracy = weighted.mean(.prediction)) %>% -->
<!--     compare_levels(accuracy, by = !!sym(variable_to_compare)) %>% -->
<!--     rename(difference_in_accuracy = accuracy)  -->

<!--   difference_data['metric'] = metric -->
<!--   difference_credible_intervals <- difference_data %>% mean_qi(difference_in_accuracy, .width = c(.95, .5)) -->
<!--   difference_credible_intervals['metric'] = metric -->

<!--   return(list("differences" = difference_data, "intervals" = difference_credible_intervals)) -->
<!-- } -->


<!-- for (accuracy_task in accuracy_tasks){ -->
<!--   subsetted_data <- subset(accuracy_data, task == accuracy_task) -->
<!--   model <- generate_accuracy_model_and_draws(subsetted_data) -->

<!--   draw_data <- subsetted_data %>% -->
<!--     add_fitted_draws(model, seed = seed, re_formula = NA) %>% -->
<!--     group_by(search, oracle, dataset, .draw) -->
<!--   draw_data$task <- accuracy_task -->
<!--   draw_data$condition <- paste(draw_data$oracle, draw_data$search, sep="_") -->
<!--   all_draws <- rbind(all_draws, draw_data) -->

<!--   fit_info <-  draw_data %>% group_by(search, oracle, dataset) %>% mean_qi(.value, .width = c(.95, .5)) -->

<!--   plot = ggplot(draw_data, aes( -->
<!--     x = .value, -->
<!--     y = condition, -->
<!--     fill = dataset, -->
<!--     alpha = 0.5 -->
<!--   )) + stat_halfeye(.width = c(.95, .5)) + -->
<!--     labs(x = "Accuracy (p_correct)", y = "Condition")  -->

<!--   filename = gsub("^.*\\.","", accuracy_task ) -->
<!--   filename = gsub(" ", "_", filename) -->
<!--   filename = paste("accuracy", filename, sep = "") -->

<!--   ggsave( -->
<!--     file = paste(filename, ".png", sep = ""), -->
<!--     plot = plot, -->
<!--     path = "../plots/posterior_draws/accuracy" -->
<!--   ) -->
<!--   write.csv(fit_info, -->
<!--             paste("../plot_data/posterior_draws/accuracy/", filename, ".csv", sep = ""), -->
<!--             row.names = FALSE) -->

<!--   predictive_data  <- subsetted_data %>% -->
<!--     add_predicted_draws(model, seed = seed, re_formula = NA) %>% -->
<!--     group_by(search, oracle, dataset, .draw) -->

<!--   for (diff in differences){ -->
<!--     vals <- get_differences_and_intervals(predictive_data, diff, accuracy_task) -->
<!--     draw_data_combined[[diff]] <- rbind(draw_data_combined[[diff]], vals$differences) -->
<!--     differences_intervals[[diff]] <- rbind(differences_intervals[[diff]], vals$intervals) -->
<!--   } -->

<!-- } -->

<!-- generate_difference_plot = function(data, xLab, yLab, filename){ -->
<!--    difference_plot <- data %>% -->
<!--       ggplot(aes(x = difference_in_accuracy, y = metric, fill = dataset, alpha = 0.5)) + -->
<!--       ylab(yLab) + -->
<!--       xlab(xLab) + -->
<!--       stat_halfeye(.width = c(.95, .5)) + -->
<!--       geom_vline(xintercept = 0, linetype = "longdash") + -->
<!--       theme_minimal() +  -->
<!--      facet_grid(. ~ dataset) -->
<!--     ggsave(file=filename, plot=difference_plot, path = "../plots/comparisons/user_response", width = 7, height = 7) -->
<!-- } -->

<!-- for (diff in differences){ -->
<!--   subsetted_draw_data <- draw_data_combined[[diff]] -->
<!--   generate_difference_plot(subsetted_draw_data,  paste0("Expected Difference in Accuracy (",subsetted_draw_data[1,diff],")"), "Task",  paste0(diff, "_accuracy_differences.png")) -->
<!--   write.csv(differences_intervals[[diff]], paste0("../plot_data/comparisons/accuracy/",diff, "_accuracy_differences.csv"), row.names = FALSE) -->
<!-- } -->


<!-- ``` -->

<!-- ```{r time_analysis}   -->
<!-- # analysis to predict time elapsed for the user to complete a certain task given a dataset, oracle, and search algorithm -->
<!-- time_data = read.csv('processed_completion_time.csv') -->
<!-- seed = 12 -->

<!-- time_data <- time_data %>% -->
<!--   mutate( -->
<!--     dataset = as.factor(dataset), -->
<!--     oracle = as.factor(oracle), -->
<!--     search = as.factor(search), -->
<!--     task = as.factor(task) -->
<!--   ) -->

<!-- time_data$log_completion_time = log(time_data$completion_time) -->

<!-- # priors for completion time of each task were derived from a pilot study -->
<!-- task_list = c("1. Find Extremum", -->
<!--               "2. Retrieve Value", -->
<!--               "3. Prediction", -->
<!--               "4. Exploration") -->

<!-- model <- brm( -->
<!--     formula = bf(log_completion_time ~ dataset * oracle * search * task), -->
<!--     prior = prior(normal(5.69, 0.69), class = Intercept), -->
<!--     chains = 2, -->
<!--     cores = 2, -->
<!--     iter = 2500, -->
<!--     warmup = 1000, -->
<!--     data = time_data, -->
<!--     file = "model_time" -->
<!--   ) -->


<!-- draw_data <- time_data %>% -->
<!--   add_fitted_draws(model, seed = seed, re_formula = NA) -->

<!-- for (task_name in task_list) { -->
<!--   draw_data_sub <- subset(draw_data, task == task_name) -->

<!--   plot <- ggplot(draw_data_sub, aes( -->
<!--     x = exp(.value), -->
<!--     y = condition, -->
<!--     fill = dataset, -->
<!--     alpha = 0.5 -->
<!--   )) + stat_halfeye(.width = c(.95, .5)) + -->
<!--     labs(x = "Time (Seconds)", y = "Condition")  -->

<!--   filename = gsub("^.*\\.","", task_name ) -->
<!--   filename = gsub(" ", "_", filename) -->
<!--   filename = paste("time", filename, sep = "") -->

<!--   ggsave( -->
<!--     file = paste(filename, ".png", sep = ""), -->
<!--     plot = plot, -->
<!--     path = "../plots/posterior_draws/time" -->
<!--   ) -->

<!--   fit_info <- draw_data_sub %>% group_by(search, oracle, dataset) %>% mean_qi(exp(.value), .width = c(.95, .5)) -->
<!--   fit_info -->
<!--   write.csv(fit_info, -->
<!--             paste("../plot_data/posterior_draws/time/", filename, ".csv", sep = ""), -->
<!--             row.names = FALSE) -->
<!-- } -->

<!-- predictive_data <- time_data %>% -->
<!--   add_predicted_draws(model, seed = seed, re_formula = NA) -->


<!-- diff_in_search_prediction <- predictive_data %>%  -->
<!--   group_by(search, task, dataset, .draw) %>% -->
<!--    summarize(time = weighted.mean(exp(.prediction))) %>% -->
<!--    compare_levels(time, by = search) %>% -->
<!--    rename(diff_in_time = time)  -->

<!-- diff_in_search_prediction_plot <- diff_in_search_prediction %>% -->
<!--       ggplot(aes(x = diff_in_time, y = task)) + -->
<!--       xlab(paste0("Time Difference (Seconds) (",diff_in_search_prediction[1,'search'],")")) + -->
<!--       ylab("Task")+ -->
<!--       stat_halfeye(.width = c(.95, .5)) + -->
<!--       geom_vline(xintercept = 0, linetype = "longdash") + -->
<!--       theme_minimal() + scale_y_discrete(limits = rev(levels(diff_in_search_prediction$task))) -->

<!-- ggsave(file="search_time_differences.png", plot=diff_in_search_prediction_plot, path = "../plots/comparisons/time", width = 7, height = 7) -->

<!-- diff_in_search_prediction_intervals <- diff_in_search_prediction %>% group_by(search, task) %>% mean_qi(diff_in_time, .width = c(.95, .5)) -->

<!-- write.csv(diff_in_search_prediction_intervals, "../plot_data/comparisons/time/search_time_differences.csv", sep="", row.names = FALSE) -->

<!-- diff_in_search_prediction_plot_split_by_dataset <- diff_in_search_prediction_plot+facet_grid(. ~ dataset) + aes(fill= dataset) -->
<!-- ggsave(file="split_by_dataset_search_time_differences.png", plot=diff_in_search_prediction_plot_split_by_dataset, path = "../plots/comparisons/time", width = 7, height = 7) -->

<!-- diff_in_search_prediction_intervals_split_by_dataset <- diff_in_search_prediction %>% group_by(search, dataset, task) %>% mean_qi(diff_in_time, .width = c(.95, .5)) -->
<!-- write.csv(diff_in_search_prediction_intervals_split_by_dataset, "../plot_data/comparisons/time/search_time_differences_split_by_dataset.csv", row.names = FALSE) -->

<!-- ############ -->

<!-- diff_in_oracle_prediction <- predictive_data %>%  -->
<!--   group_by(oracle, task, dataset, .draw) %>% -->
<!--    summarize(time = weighted.mean(exp(.prediction))) %>% -->
<!--    compare_levels(time, by = oracle) %>% -->
<!--    rename(diff_in_time = time)  -->

<!-- diff_in_oracle_prediction_plot <- diff_in_oracle_prediction %>% -->
<!--       ggplot(aes(x = diff_in_time, y = task)) + -->
<!--       xlab(paste0("Time Difference (Seconds) (",diff_in_oracle_prediction[1,'oracle'],")")) + -->
<!--       ylab("Task")+ -->
<!--       stat_halfeye(.width = c(.95, .5)) + -->
<!--       geom_vline(xintercept = 0, linetype = "longdash") + -->
<!--       theme_minimal() + scale_y_discrete(limits = rev(levels(diff_in_oracle_prediction$task))) -->

<!-- ggsave(file="oracle_time_differences.png", plot=diff_in_oracle_prediction_plot, path = "../plots/comparisons/time", width = 7, height = 7) -->

<!-- diff_in_oracle_prediction_intervals <- diff_in_oracle_prediction %>% group_by(oracle, task) %>% mean_qi(diff_in_time, .width = c(.95, .5)) -->

<!-- write.csv(diff_in_oracle_prediction_intervals, "../plot_data/comparisons/time/oracle_time_differences.csv", sep="", row.names = FALSE) -->

<!-- diff_in_oracle_prediction_plot_split_by_dataset <- diff_in_oracle_prediction_plot+facet_grid(. ~ dataset) + aes(fill= dataset) -->
<!-- ggsave(file="split_by_dataset_oracle_time_differences.png", plot=diff_in_oracle_prediction_plot_split_by_dataset, path = "../plots/comparisons/time", width = 7, height = 7) -->

<!-- diff_in_oracle_prediction_intervals_split_by_dataset <- diff_in_oracle_prediction %>% group_by(oracle, dataset, task) %>% mean_qi(diff_in_time, .width = c(.95, .5)) -->
<!-- write.csv(diff_in_oracle_prediction_intervals_split_by_dataset, "../plot_data/comparisons/time/oracle_time_differences_split_by_dataset.csv", row.names = FALSE) -->

<!-- ######## -->


<!-- plot <- draw_data %>% ggplot(aes( -->
<!--     x = exp(.value), -->
<!--     y = task, -->
<!--     fill = search, -->
<!--     alpha = 0.5 -->
<!--   )) + stat_halfeye(.width = c(.95, .5)) + -->
<!--     labs(x = "Time (Seconds)", y = "Task") +  facet_grid(. ~ dataset) -->

<!--  ggsave( -->
<!--     file = paste("all_tasks_search.png", sep = ""), -->
<!--     plot = plot, -->
<!--     path = "../plots/posterior_draws/time" -->
<!--   ) -->
<!-- ``` -->







